author :
  name : Milan Zupunski
  email : mzupunski@yahoo.com
  github : milanzupunski
  twitter : milanzupunski
  bluesky : milanzupunski.bsky.social
markdown: milanzupunski
permalink: /blog/:year/:month/:day/:title
