author :
  name : Milan Zupunski
  email : milan.zupunski@hhu.de
  github : milanzupunski
  twitter : milanzupunski
  Bluesky-social : milanzupunski.bsky.social
markdown: milanzupunski
permalink: /blog/:year/:month/:day/:title
